// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (habit_id, day)
VALUES ($1, $2)
`

type CreateEntryParams struct {
	HabitID int32
	Day     pgtype.Date
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.Exec(ctx, createEntry, arg.HabitID, arg.Day)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE habit_id = $1 AND day = $2
`

type DeleteEntryParams struct {
	HabitID int32
	Day     pgtype.Date
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.Exec(ctx, deleteEntry, arg.HabitID, arg.Day)
	return err
}

const entryExists = `-- name: EntryExists :one
SELECT EXISTS(
    SELECT 1 FROM entries WHERE habit_id = $1 AND day = $2
) AS exists
`

type EntryExistsParams struct {
	HabitID int32
	Day     pgtype.Date
}

func (q *Queries) EntryExists(ctx context.Context, arg EntryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, entryExists, arg.HabitID, arg.Day)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const todayPoints = `-- name: TodayPoints :one
SELECT COALESCE(SUM(h.points), 0)::int AS total
FROM entries e
JOIN habits h ON h.id = e.habit_id
WHERE e.day = $1
`

func (q *Queries) TodayPoints(ctx context.Context, day pgtype.Date) (int32, error) {
	row := q.db.QueryRow(ctx, todayPoints, day)
	var total int32
	err := row.Scan(&total)
	return total, err
}
