// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: habits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (name, description, points)
VALUES ($1, $2, $3)
RETURNING id, name, description, points, created_at
`

type CreateHabitParams struct {
	Name        string
	Description *string
	Points      int32
}

type CreateHabitRow struct {
	ID          int32
	Name        string
	Description *string
	Points      int32
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (CreateHabitRow, error) {
	row := q.db.QueryRow(ctx, createHabit, arg.Name, arg.Description, arg.Points)
	var i CreateHabitRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Points,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHabit, id)
	return err
}

const listHabits = `-- name: ListHabits :many
SELECT id, name, description, points, created_at
FROM habits
ORDER BY created_at ASC
`

type ListHabitsRow struct {
	ID          int32
	Name        string
	Description *string
	Points      int32
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListHabits(ctx context.Context) ([]ListHabitsRow, error) {
	rows, err := q.db.Query(ctx, listHabits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHabitsRow
	for rows.Next() {
		var i ListHabitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Points,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
