// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Entry struct {
	ID        int32
	HabitID   int32
	Day       pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type Habit struct {
	ID          int32
	Name        string
	Description *string
	Points      int32
	Target      int32
	Period      string
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
